---
language: python
python: "3.6"
matrix:
  fast_finish: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt
install:
  - pip install ansible ansible-lint
  - pip --version
  - python --version
  - ansible --version
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  - "printf 'requests==2.18.4' > /opt/requirements.txt"
script:
  - ansible-lint tasks/main.yml
  - ansible-playbook -i tests/inventory --syntax-check --list-tasks tests/test.yml
  - ansible-playbook -i tests/inventory --connection=local --become -vvvv tests/test.yml -u root
  - >
    ansible-playbook -i tests/inventory --connection=local --become -vvvv tests/test.yml -u root
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - stat /usr/local/pythonz/pythons/CPython-3.6.2/bin/python
  - stat /usr/local/pythonz/pythons/CPython-3.6.3/bin/python
  - /opt/test_env/env_1/bin/python --version == 'Python 3.6.1'
  - /opt/test_env/env_1/bin/pip freeze | grep -q 'requests==2.18.4' && exit 0 || exit 1
  - /opt/test_env/env_2/bin/python --version == 'Python 3.6.2'
  - /opt/test_env/env_2/bin/pip --version == '8.0.0'
